// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBkKzEXME_g3NB5BLryzgP6lw7lyQ2i24',
    appId: '1:924194140304:web:c0a7070cabe71b92ee2815',
    messagingSenderId: '924194140304',
    projectId: 'project-hellping-123',
    authDomain: 'project-hellping-123.firebaseapp.com',
    storageBucket: 'project-hellping-123.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHXgxN1eXPo5qfN9E3eNIyvwnf0EQ5778',
    appId: '1:924194140304:android:d93cfd8552d03955ee2815',
    messagingSenderId: '924194140304',
    projectId: 'project-hellping-123',
    storageBucket: 'project-hellping-123.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJO4lwqfF_c3plzPcJmbwhULE5oO7iCCw',
    appId: '1:924194140304:ios:e959a0d017278d03ee2815',
    messagingSenderId: '924194140304',
    projectId: 'project-hellping-123',
    storageBucket: 'project-hellping-123.firebasestorage.app',
    iosBundleId: 'com.example.projectHellping',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJO4lwqfF_c3plzPcJmbwhULE5oO7iCCw',
    appId: '1:924194140304:ios:e959a0d017278d03ee2815',
    messagingSenderId: '924194140304',
    projectId: 'project-hellping-123',
    storageBucket: 'project-hellping-123.firebasestorage.app',
    iosBundleId: 'com.example.projectHellping',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBkKzEXME_g3NB5BLryzgP6lw7lyQ2i24',
    appId: '1:924194140304:web:ee123c268fd4f6abee2815',
    messagingSenderId: '924194140304',
    projectId: 'project-hellping-123',
    authDomain: 'project-hellping-123.firebaseapp.com',
    storageBucket: 'project-hellping-123.firebasestorage.app',
  );

}